version = 1

test_patterns = [
    "*.py",
    "*/chat/*.py",
    "*/tinderforeduapp/*.py",
    "*/tinderforedu/*.py"
]

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"
