# Generated by Django 3.0.2 on 2020-01-15 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tinderforeduapp', '0002_auto_20200112_1831'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={},
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={},
        ),
    ]
