# Generated by Django 3.0 on 2020-01-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinderforeduapp', '0003_auto_20200115_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='age',
            field=models.TextField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='school',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
