# Generated by Django 3.0 on 2020-02-23 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tinderforeduapp', '0010_auto_20200212_1840'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(blank=True, max_length=200)),
                ('comment', models.TextField(blank=True, max_length=5000)),
                ('star', models.TextField(blank=True, max_length=5)),
            ],
        ),
        migrations.AddField(
            model_name='userinfo',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tinderforeduapp.comment'),
        ),
    ]
