# Generated by Django 3.0.2 on 2020-02-23 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinderforeduapp', '0010_auto_20200212_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='massage_list',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='match_request',
            field=models.IntegerField(default=0),
        ),
    ]
