# Generated by Django 3.0 on 2020-02-23 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tinderforeduapp', '0012_auto_20200223_1645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='customer',
            new_name='user',
        ),
    ]
