# Generated by Django 3.0 on 2020-02-23 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tinderforeduapp', '0014_auto_20200223_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='whocomment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whocomment', to='tinderforeduapp.Userinfo'),
        ),
    ]
