# Generated by Django 3.0 on 2020-02-23 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tinderforeduapp', '0017_auto_20200223_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commentto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commentto', to='tinderforeduapp.Userinfo'),
        ),
    ]
