# Generated by Django 3.0 on 2020-02-23 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinderforeduapp', '0018_auto_20200223_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='star_value',
            field=models.TextField(max_length=10, null=True, verbose_name='star'),
        ),
    ]
