# Generated by Django 3.0 on 2020-02-23 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinderforeduapp', '0019_comment_star_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_value',
            field=models.TextField(null=True, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='star_value',
            field=models.TextField(null=True, verbose_name='star'),
        ),
    ]
