# Generated by Django 3.0 on 2020-02-23 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tinderforeduapp', '0020_auto_20200223_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commentto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userinfo', to='tinderforeduapp.Userinfo'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='whocomment',
            field=models.TextField(null=True),
        ),
    ]
