# Generated by Django 3.0.2 on 2020-02-24 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinderforeduapp', '0027_comment_star'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='massage_list',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='match_request',
            field=models.IntegerField(default=0),
        ),
    ]
