# Generated by Django 3.0.2 on 2020-03-11 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tinderforeduapp', '0028_auto_20200224_0558'),
        ('tinderforeduapp', '0011_auto_20200223_1605'),
    ]

    operations = [
    ]
