# Generated by Django 3.0.2 on 2020-03-11 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinderforeduapp', '0029_merge_20200311_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='good_subject',
            field=models.ManyToManyField(blank=True, related_name='Userinfos', to='tinderforeduapp.Subject'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='match',
            field=models.ManyToManyField(blank=True, to='tinderforeduapp.match_class'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='request',
            field=models.ManyToManyField(blank=True, to='tinderforeduapp.request_class'),
        ),
    ]
