# Generated by Django 3.0.3 on 2020-03-19 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinderforeduapp', '0030_auto_20200311_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='fb_link',
            field=models.TextField(null=True),
        ),
    ]
