# Generated by Django 3.0.4 on 2020-03-24 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinderforeduapp', '0032_subject_subject_keep'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='schoolkey',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
