# Generated by Django 3.0.4 on 2020-03-24 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tinderforeduapp', '0032_auto_20200325_0024'),
        ('tinderforeduapp', '0033_userinfo_schoolkey'),
    ]

    operations = [
    ]
