# Generated by Django 3.0.3 on 2020-03-25 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinderforeduapp', '0034_merge_20200325_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='request_class',
            name='request_message',
            field=models.TextField(blank=True, max_length=600),
        ),
    ]
