# Generated by Django 3.0.4 on 2020-03-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinderforeduapp', '0035_request_class_request_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='picutre',
            field=models.ImageField(blank=True, default='images/user_pic/default.png', upload_to='images/user_pic'),
        ),
    ]
