# Generated by Django 3.0.4 on 2020-03-25 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tinderforeduapp', '0036_userinfo_picutre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='picutre',
        ),
        migrations.CreateModel(
            name='Profilepic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.png', upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tinderforeduapp.Userinfo')),
            ],
        ),
    ]
