# Generated by Django 3.0.4 on 2020-03-25 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinderforeduapp', '0037_auto_20200325_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilepic',
            name='image',
        ),
        migrations.AddField(
            model_name='profilepic',
            name='images',
            field=models.ImageField(default='images/user_pic/default.png', upload_to='profile_pics'),
        ),
    ]
