# Generated by Django 3.0.3 on 2020-03-25 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tinderforeduapp', '0040_auto_20200325_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepic',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
