# Generated by Django 3.0.3 on 2020-03-25 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinderforeduapp', '0042_auto_20200325_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepic',
            name='images',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
    ]
