# Generated by Django 3.0.3 on 2020-03-25 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinderforeduapp', '0043_auto_20200325_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepic',
            name='images',
            field=models.ImageField(default='default.png', upload_to='media/'),
        ),
    ]
