# Generated by Django 3.0.3 on 2020-03-25 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tinderforeduapp', '0045_auto_20200325_2208'),
        ('tinderforeduapp', '0045_auto_20200325_2226'),
    ]

    operations = [
    ]
