# Generated by Django 3.0.3 on 2020-03-25 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinderforeduapp', '0046_merge_20200325_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='match_class',
            name='youself',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='request_class',
            name='whorecive',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
