# Generated by Django 2.2.8 on 2020-01-15 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinderforeduapp', '0003_auto_20200115_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='good_subject',
            field=models.ManyToManyField(to='tinderforeduapp.Subject'),
        ),
    ]
