# Generated by Django 3.0.2 on 2020-01-29 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinderforeduapp', '0007_profile_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='fullname',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='lastname',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
