# Generated by Django 3.0.2 on 2020-02-12 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinderforeduapp', '0008_auto_20200129_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='request_class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_list', models.TextField(blank=True, max_length=200)),
                ('match_list', models.TextField(blank=True, max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='userinfo',
            name='request',
            field=models.ManyToManyField(to='tinderforeduapp.request_class'),
        ),
    ]
