# Generated by Django 3.0.3 on 2020-02-13 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savechat',
            name='user1',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='savechat',
            name='user2',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
