# Generated by Django 3.0.3 on 2020-02-16 18:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20200213_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='savechat',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='savechat',
            name='chat',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='savechat',
            name='name',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='savechat',
            name='user1',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='savechat',
            name='user2',
            field=models.TextField(blank=True),
        ),
    ]
